var jsonData = [
    {
        "q" : "A memory buffer used to accommodate a speed differential is called _____",
        "opt1" : "cache",
        "opt2" : "disk buffer",
        "opt3" : "accumulator",
        "answer" : "cache"
    },
    {
        "q" : "Run time mapping from virtual to physical address is done by ____________",
        "opt1" : "Memory management unit",
        "opt2" : "CPU ",
        "opt3" : "PCI",
        "answer" : "Memory management unit"
    },
    {
        "q" : "Memory management technique in which system stores and retrieves data from secondary storage for use in main memory is called? ",
        "opt1" : "paging",
        "opt2" : "mapping",
        "opt3" : "fragmentation",
        "answer" :"paging"
    },
    {
        "q" : " Which one of the following is the address generated by CPU?",
        "opt1" : "logical address",
        "opt2" : "Physical address ",
        "opt3" : "Dynamic address",
        "answer" : "logical address"
    },
    {
        "q" : "The address of a page table in memory is pointed by ____________",
        "opt1" : "page table base register",
        "opt2" : "page register ",
        "opt3" : "stack pointer",
        "answer" : "page table base register"
    }

    
];